### ISSUE TITLE
Alpha 63 does not work with a parameter scan list

### ISSUE THREAD

**Issue by lesloew** [virtualcell/vcell#440]
UPDATE: apparently the model won't save for any parameter override; it doesn't have to be a scan. 
See Model "FRAP_Membrane". Parameter scans fail; they have quotation marks around them in the list and Ion thought this might be part of the issue. Local run of the same sim works fine; also a similar model was created in Rel and it also works (but not if it is read into Alpha). Additionally, saving the model in Alpha (after making any slight change, e.g. moving species in the reaction diagram) produces the following error:
DataAccessException-RPC method DbRequestQueue:saveBioModel() failed: response status: 500
reason: internal error invoking DbRequestQueue:saveBioModel(): java.lang.RuntimeException

**Comment by danv61** [comment]
Fixed in commit 9f1c890
The problem was a NullPointerException caused by a null SimulationOwner.

**Comment by lesloew** [comment]
We need to deploy a new alpha for the changes to take effect. We'll do that today.
This won't solve the time limitation problem on very large rule-based models, but at least our users should be able to save models with parameter scans in alpha again.

Best,
Dan
________________________________

**Comment by lesloew** [comment]
Yes, the sims now run and the model can be saved in Alpha 65,
Thanks,
Les

**Comment by lesloew** [comment]
Still doesn’t work on Alpha 63. Does a new Alpha need to be deployed?

From: Dan Vasilescu ***@***.***>
Reply-To: virtualcell/vcell ***@***.***>
Date: Tuesday, October 4, 2022 at 4:00 PM
To: virtualcell/vcell ***@***.***>
Cc: "Loew,Leslie M." ***@***.***>, Assign ***@***.***>
Subject: Re: [virtualcell/vcell] Alpha 63 does not work with a parameter scan list (Issue #440)

*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

Closed #440<https://urldefense.com/v3/__https:/github.com/virtualcell/vcell/issues/440__;!!Cn_UX_p3!mbcgwvK3wdC2g_yM1VdK1g_EToW3xib6YNimY8kGjidLR56hnbiitYqwTnGW3G4NB9OoUkRQn46zlkQgG0P3$> as completed.

**Comment by danv61** [comment]
This should work on Alpha 65 or higher. I just tested it on Alpha 68 and it seems to work, I tested with parameter scans formatted as List and Range. The model can be saved and the simulations run (with either green or blue buttons).

**Comment by lesloew** [comment]
Confirmed. You can close the issue.
Thanks,
Les

From: Dan Vasilescu ***@***.***>
Reply-To: virtualcell/vcell ***@***.***>
Date: Tuesday, October 11, 2022 at 1:23 PM
To: virtualcell/vcell ***@***.***>
Cc: "Loew,Leslie M." ***@***.***>, Assign ***@***.***>
Subject: Re: [virtualcell/vcell] Alpha 63 does not work with a parameter scan list (Issue #440)

*** Attention: This is an external email. Use caution responding, opening attachments or clicking on links. ***

This should work on Alpha 65 or higher. I just tested it on Alpha 68 and it seems to work, I tested with parameter scans formatted as List and Range. The model can be saved and the simulations run (with either green or blue buttons).
